Small changes so I could put faceting in
but the faceting itself is commented out. Still getting error

  synapseclient.core.exceptions.SynapseHTTPError: 400 Client Error:
  Cannot update row: 16745 because it does not exist.