With @thomasyu888's modifications from gist
https://gist.github.com/thomasyu888/d35d4bca0c693337aee99d4e29b98642

Worked once (maybe with some additional changes, I can't recall), but
now I'm getting
  synapseclient.core.exceptions.SynapseHTTPError: 400 Client Error:
  Cannot update row: 16745 because it does not exist.